In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import pickle
import plotly.graph_objects as go
pd.options.plotting.backend = "plotly"
import scipy.stats as stats
from numpy import linspace
from numpy.core.umath import pi
from sklearn.metrics import adjusted_mutual_info_score
from sklearn.metrics import mutual_info_score

In [2]:
parent_df_path = 'usage_per_user/'

with open(parent_df_path+'joh_df.pkl', 'rb') as f:
    joh_per_usage = pickle.load(f)
    
with open(parent_df_path+'lon_df.pkl', 'rb') as f:
    lon_per_usage = pickle.load(f)
    
with open(parent_df_path+'nyc_df.pkl', 'rb') as f:
    nyc_per_usage = pickle.load(f)
    
with open(parent_df_path+'ran_df.pkl', 'rb') as f:
    ran_per_usage = pickle.load(f)


all_usage = pd.concat([joh_per_usage,lon_per_usage,nyc_per_usage,ran_per_usage],ignore_index = True)

In [3]:
all_usage.drop(labels = all_usage[all_usage.ethnicity.eq('other')].index,inplace =True)
all_usage.reset_index(inplace = True,drop = True)
all_usage

,#Ô∏è‚É£,*Ô∏è‚É£,0Ô∏è‚É£,1Ô∏è‚É£,2Ô∏è‚É£,3Ô∏è‚É£,4Ô∏è‚É£,5Ô∏è‚É£,6Ô∏è‚É£,7Ô∏è‚É£,...,üß∫,üßª,üßº,üßΩ,üßæ,üßø,tweets_contain_emoji,total_tweets,gender,ethnicity
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,62.0,111.0,female,black
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,female,black
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,566.0,945.0,female,black
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,251.0,444.0,male,white
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,410.0,887.0,female,black
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18684,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,117.0,3121.0,female,hispanic
18685,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,551.0,3072.0,female,black
18686,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1055.0,2482.0,male,asian
18687,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,905.0,2752.0,female,white
18688,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,15.0,3206.0,male,white

In [4]:
emoji_prop = all_usage.drop(columns = ['tweets_contain_emoji','total_tweets','gender','ethnicity'])
for index, row in emoji_prop.iterrows():
    s = emoji_prop.loc[index].sum()
    if s!=0:
        emoji_prop.loc[index] = emoji_prop.loc[index]/s
    else:
        emoji_prop.loc[index] = 0

emoji_prop_gender = emoji_prop
emoji_prop_gender['gender'] = all_usage['gender']
emoji_prop_gender

,#Ô∏è‚É£,*Ô∏è‚É£,0Ô∏è‚É£,1Ô∏è‚É£,2Ô∏è‚É£,3Ô∏è‚É£,4Ô∏è‚É£,5Ô∏è‚É£,6Ô∏è‚É£,7Ô∏è‚É£,...,üß∑,üß∏,üßπ,üß∫,üßª,üßº,üßΩ,üßæ,üßø,gender
0,0.0,0.0,0.0,0.00000,0.0,0.00000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,female
1,0.0,0.0,0.0,0.00000,0.0,0.00000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,female
2,0.0,0.0,0.0,0.00000,0.0,0.00000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,female
3,0.0,0.0,0.0,0.00000,0.0,0.00000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,male
4,0.0,0.0,0.0,0.00000,0.0,0.00000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,female
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18684,0.0,0.0,0.0,0.00000,0.0,0.00000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,female
18685,0.0,0.0,0.0,0.00000,0.0,0.00000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,female
18686,0.0,0.0,0.0,0.00034,0.0,0.00034,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,male
18687,0.0,0.0,0.0,0.00000,0.0,0.00000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,female
18688,0.0,0.0,0.0,0.00000,0.0,0.00000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,male

In [5]:
gender_bias = emoji_prop_gender.loc[emoji_prop_gender['gender'] == 'male'].mean() - emoji_prop_gender.loc[emoji_prop_gender['gender'] == 'female'].mean()

In [6]:
MI_by_gender = {}

for index,emoji in enumerate (emoji_prop_gender.drop(columns=['gender']).columns):
    X = emoji_prop_gender[emoji]
#     X = X.round(decimals=1)
    Y = emoji_prop_gender['gender']

#     MI_by_gender[emoji] = mutual_info_score(X,Y) 
    MI_by_gender[emoji] = adjusted_mutual_info_score(X,Y) 

MI_by_gender_pd = pd.DataFrame(data=sorted(MI_by_gender.items(), key=lambda kv: kv[1],reverse= True),columns=['Emoji','MI'])

In [7]:
for index,emoji in enumerate(MI_by_gender_pd['Emoji']):
    if gender_bias[emoji] > 0:
        MI_by_gender_pd.at[index,'gender'] = 'male'
    elif gender_bias[emoji] < 0:
        MI_by_gender_pd.at[index,'gender'] = 'female'
    else:
        MI_by_gender_pd.at[index,'gender'] = 'same'

In [8]:
MI_by_gender_pd[MI_by_gender_pd.gender.eq('male')][:10]

    Emoji        MI gender
1    ü§∑‚Äç‚ôÇÔ∏è  0.006399   male
4    ü§¶‚Äç‚ôÇÔ∏è  0.005658   male
6       ‚öΩ  0.005409   male
10      üêê  0.004916   male
14      üî¥  0.004426   male
15  ü§¶üèª‚Äç‚ôÇÔ∏è  0.004401   male
19      üîµ  0.004099   male
26      üöÄ  0.003471   male
27      üëç  0.003395   male
28      üèÜ  0.003328   male

In [9]:
MI_by_gender_pd[MI_by_gender_pd.gender.eq('female')][:10]

    Emoji        MI  gender
0       üíï  0.008910  female
2       üå∏  0.006241  female
3       üíó  0.005924  female
5       üòò  0.005605  female
7       üíú  0.005395  female
8   ü§∑üèΩ‚Äç‚ôÄÔ∏è  0.005320  female
9       üíã  0.004949  female
11      üíñ  0.004872  female
12      ‚ú®  0.004701  female
13      ‚ù§  0.004429  female